###
POST http://localhost:5000/getbankaccount
Content-Type: application/json

{
    "userid" : "1"
}

###
GET http://localhost:5000/getusers

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "username" : "AcerDBS",
    "password" : "Top5Seeder"
}